# Generated by Django 3.2.9 on 2021-11-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_defaultsubscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128)),
                ('plan_name', models.CharField(max_length=128)),
                ('plan_price', models.IntegerField(max_length=128)),
                ('cycle', models.CharField(max_length=128)),
                ('head_count', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('service_id', models.CharField(max_length=128, null=True)),
                ('image', models.CharField(max_length=1024, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user_api.user')),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
    ]
