# Generated by Django 3.2.9 on 2021-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_auto_20211128_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_price',
            field=models.IntegerField(),
        ),
    ]
